/**
 * Created by brance on 2016/5/10.
 */
(function(){

    //1.how to understanding services?

    /*Angular services are substitutable objects that are wired together using dependency injection (DI).
     You can use services to organize and share code across your app.
*/

    //2.service properties:

    //A:Lazily instantiated – Angular only instantiates a service when an application component depends
    // on it.

    //B:Singletons – Each component dependent on a service gets a reference to the single instance
    // generated by the service factory.


})();